"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2018 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.assistant.embedded.v1alpha2 import embedded_assistant_pb2 as _embedded_assistant_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EmbeddedAssistantStub:
    """Service that implements the Google Assistant API."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EmbeddedAssistantAsyncStub: ...
    Assist: _grpc.StreamStreamMultiCallable[_embedded_assistant_pb2.AssistRequest, _embedded_assistant_pb2.AssistResponse]
    """Initiates or continues a conversation with the embedded Assistant Service.
    Each call performs one round-trip, sending an audio request to the service
    and receiving the audio response. Uses bidirectional streaming to receive
    results, such as the `END_OF_UTTERANCE` event, while sending audio.

    A conversation is one or more gRPC connections, each consisting of several
    streamed requests and responses.
    For example, the user says *Add to my shopping list* and the Assistant
    responds *What do you want to add?*. The sequence of streamed requests and
    responses in the first gRPC message could be:

    *   AssistRequest.config
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistResponse.event_type.END_OF_UTTERANCE
    *   AssistResponse.speech_results.transcript "add to my shopping list"
    *   AssistResponse.dialog_state_out.microphone_mode.DIALOG_FOLLOW_ON
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out


    The user then says *bagels* and the Assistant responds
    *OK, I've added bagels to your shopping list*. This is sent as another gRPC
    connection call to the `Assist` method, again with streamed requests and
    responses, such as:

    *   AssistRequest.config
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistResponse.event_type.END_OF_UTTERANCE
    *   AssistResponse.dialog_state_out.microphone_mode.CLOSE_MICROPHONE
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out

    Although the precise order of responses is not guaranteed, sequential
    `AssistResponse.audio_out` messages will always contain sequential portions
    of audio.
    """

@_typing.type_check_only
class EmbeddedAssistantAsyncStub(EmbeddedAssistantStub):
    """Service that implements the Google Assistant API."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Assist: _aio.StreamStreamMultiCallable[_embedded_assistant_pb2.AssistRequest, _embedded_assistant_pb2.AssistResponse]  # type: ignore[assignment]
    """Initiates or continues a conversation with the embedded Assistant Service.
    Each call performs one round-trip, sending an audio request to the service
    and receiving the audio response. Uses bidirectional streaming to receive
    results, such as the `END_OF_UTTERANCE` event, while sending audio.

    A conversation is one or more gRPC connections, each consisting of several
    streamed requests and responses.
    For example, the user says *Add to my shopping list* and the Assistant
    responds *What do you want to add?*. The sequence of streamed requests and
    responses in the first gRPC message could be:

    *   AssistRequest.config
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistResponse.event_type.END_OF_UTTERANCE
    *   AssistResponse.speech_results.transcript "add to my shopping list"
    *   AssistResponse.dialog_state_out.microphone_mode.DIALOG_FOLLOW_ON
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out


    The user then says *bagels* and the Assistant responds
    *OK, I've added bagels to your shopping list*. This is sent as another gRPC
    connection call to the `Assist` method, again with streamed requests and
    responses, such as:

    *   AssistRequest.config
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistRequest.audio_in
    *   AssistResponse.event_type.END_OF_UTTERANCE
    *   AssistResponse.dialog_state_out.microphone_mode.CLOSE_MICROPHONE
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out
    *   AssistResponse.audio_out

    Although the precise order of responses is not guaranteed, sequential
    `AssistResponse.audio_out` messages will always contain sequential portions
    of audio.
    """

class EmbeddedAssistantServicer(metaclass=_abc_1.ABCMeta):
    """Service that implements the Google Assistant API."""

    @_abc_1.abstractmethod
    def Assist(
        self,
        request_iterator: _MaybeAsyncIterator[_embedded_assistant_pb2.AssistRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_embedded_assistant_pb2.AssistResponse], _abc.AsyncIterator[_embedded_assistant_pb2.AssistResponse]]:
        """Initiates or continues a conversation with the embedded Assistant Service.
        Each call performs one round-trip, sending an audio request to the service
        and receiving the audio response. Uses bidirectional streaming to receive
        results, such as the `END_OF_UTTERANCE` event, while sending audio.

        A conversation is one or more gRPC connections, each consisting of several
        streamed requests and responses.
        For example, the user says *Add to my shopping list* and the Assistant
        responds *What do you want to add?*. The sequence of streamed requests and
        responses in the first gRPC message could be:

        *   AssistRequest.config
        *   AssistRequest.audio_in
        *   AssistRequest.audio_in
        *   AssistRequest.audio_in
        *   AssistRequest.audio_in
        *   AssistResponse.event_type.END_OF_UTTERANCE
        *   AssistResponse.speech_results.transcript "add to my shopping list"
        *   AssistResponse.dialog_state_out.microphone_mode.DIALOG_FOLLOW_ON
        *   AssistResponse.audio_out
        *   AssistResponse.audio_out
        *   AssistResponse.audio_out


        The user then says *bagels* and the Assistant responds
        *OK, I've added bagels to your shopping list*. This is sent as another gRPC
        connection call to the `Assist` method, again with streamed requests and
        responses, such as:

        *   AssistRequest.config
        *   AssistRequest.audio_in
        *   AssistRequest.audio_in
        *   AssistRequest.audio_in
        *   AssistResponse.event_type.END_OF_UTTERANCE
        *   AssistResponse.dialog_state_out.microphone_mode.CLOSE_MICROPHONE
        *   AssistResponse.audio_out
        *   AssistResponse.audio_out
        *   AssistResponse.audio_out
        *   AssistResponse.audio_out

        Although the precise order of responses is not guaranteed, sequential
        `AssistResponse.audio_out` messages will always contain sequential portions
        of audio.
        """

def add_EmbeddedAssistantServicer_to_server(servicer: EmbeddedAssistantServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
