"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2018 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AssistRequest(_message.Message):
    """The top-level message sent by the client. Clients must send at least two, and
    typically numerous `AssistRequest` messages. The first message must
    contain a `config` message and must not contain `audio_in` data. All
    subsequent messages must contain `audio_in` data and must not contain a
    `config` message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_IN_FIELD_NUMBER: _builtins.int
    audio_in: _builtins.bytes
    """The audio data to be recognized. Sequential chunks of audio data are sent
    in sequential `AssistRequest` messages. The first `AssistRequest`
    message must not contain `audio_in` data and all subsequent
    `AssistRequest` messages must contain `audio_in` data. The audio bytes
    must be encoded as specified in `AudioInConfig`.
    Audio must be sent at approximately real-time (16000 samples per second).
    An error will be returned if audio is sent significantly faster or
    slower.
    """
    @_builtins.property
    def config(self) -> Global___AssistConfig:
        """The `config` message provides information to the recognizer that
        specifies how to process the request.
        The first `AssistRequest` message must contain a `config` message.
        """

    def __init__(
        self,
        *,
        config: Global___AssistConfig | None = ...,
        audio_in: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_in", b"audio_in", "config", b"config", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_in", b"audio_in", "config", b"config", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["config", "audio_in"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___AssistRequest: _TypeAlias = AssistRequest  # noqa: Y015

@_typing.final
class AssistResponse(_message.Message):
    """The top-level message received by the client. A series of one or more
    `AssistResponse` messages are streamed back to the client.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _EventType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AssistResponse._EventType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        EVENT_TYPE_UNSPECIFIED: AssistResponse._EventType.ValueType  # 0
        """No event specified."""
        END_OF_UTTERANCE: AssistResponse._EventType.ValueType  # 1
        """This event indicates that the server has detected the end of the user's
        speech utterance and expects no additional speech. Therefore, the server
        will not process additional audio (although it may subsequently return
        additional results). The client should stop sending additional audio
        data, half-close the gRPC connection, and wait for any additional results
        until the server closes the gRPC connection.
        """

    class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper):
        """Indicates the type of event."""

    EVENT_TYPE_UNSPECIFIED: AssistResponse.EventType.ValueType  # 0
    """No event specified."""
    END_OF_UTTERANCE: AssistResponse.EventType.ValueType  # 1
    """This event indicates that the server has detected the end of the user's
    speech utterance and expects no additional speech. Therefore, the server
    will not process additional audio (although it may subsequently return
    additional results). The client should stop sending additional audio
    data, half-close the gRPC connection, and wait for any additional results
    until the server closes the gRPC connection.
    """

    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    AUDIO_OUT_FIELD_NUMBER: _builtins.int
    SCREEN_OUT_FIELD_NUMBER: _builtins.int
    DEVICE_ACTION_FIELD_NUMBER: _builtins.int
    SPEECH_RESULTS_FIELD_NUMBER: _builtins.int
    DIALOG_STATE_OUT_FIELD_NUMBER: _builtins.int
    DEBUG_INFO_FIELD_NUMBER: _builtins.int
    event_type: Global___AssistResponse.EventType.ValueType
    """*Output-only* Indicates the type of event."""
    @_builtins.property
    def audio_out(self) -> Global___AudioOut:
        """*Output-only* The audio containing the Assistant's response to the query."""

    @_builtins.property
    def screen_out(self) -> Global___ScreenOut:
        """*Output-only* Contains the Assistant's visual response to the query."""

    @_builtins.property
    def device_action(self) -> Global___DeviceAction:
        """*Output-only* Contains the action triggered by the query with the
        appropriate payloads and semantic parsing.
        """

    @_builtins.property
    def speech_results(self) -> _containers.RepeatedCompositeFieldContainer[Global___SpeechRecognitionResult]:
        """*Output-only* This repeated list contains zero or more speech recognition
        results that correspond to consecutive portions of the audio currently
        being processed, starting with the portion corresponding to the earliest
        audio (and most stable portion) to the portion corresponding to the most
        recent audio. The strings can be concatenated to view the full
        in-progress response. When the speech recognition completes, this list
        will contain one item with `stability` of `1.0`.
        """

    @_builtins.property
    def dialog_state_out(self) -> Global___DialogStateOut:
        """*Output-only* Contains output related to the user's query."""

    @_builtins.property
    def debug_info(self) -> Global___DebugInfo:
        """*Output-only* Debugging info for developer. Only returned if request set
        `return_debug_info` to true.
        """

    def __init__(
        self,
        *,
        event_type: Global___AssistResponse.EventType.ValueType = ...,
        audio_out: Global___AudioOut | None = ...,
        screen_out: Global___ScreenOut | None = ...,
        device_action: Global___DeviceAction | None = ...,
        speech_results: _abc.Iterable[Global___SpeechRecognitionResult] | None = ...,
        dialog_state_out: Global___DialogStateOut | None = ...,
        debug_info: Global___DebugInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_out", b"audio_out", "debug_info", b"debug_info", "device_action", b"device_action", "dialog_state_out", b"dialog_state_out", "screen_out", b"screen_out"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_out", b"audio_out", "debug_info", b"debug_info", "device_action", b"device_action", "dialog_state_out", b"dialog_state_out", "event_type", b"event_type", "screen_out", b"screen_out", "speech_results", b"speech_results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssistResponse: _TypeAlias = AssistResponse  # noqa: Y015

@_typing.final
class DebugInfo(_message.Message):
    """Debug info for developer. Only returned if request set `return_debug_info`
    to true.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AOG_AGENT_TO_ASSISTANT_JSON_FIELD_NUMBER: _builtins.int
    aog_agent_to_assistant_json: _builtins.str
    """The original JSON response from an Action-on-Google agent to Google server.
    See
    https://developers.google.com/actions/reference/rest/Shared.Types/AppResponse.
    It will only be populated if the request maker owns the AoG project and the
    AoG project is in preview mode.
    """
    def __init__(
        self,
        *,
        aog_agent_to_assistant_json: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aog_agent_to_assistant_json", b"aog_agent_to_assistant_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DebugInfo: _TypeAlias = DebugInfo  # noqa: Y015

@_typing.final
class AssistConfig(_message.Message):
    """Specifies how to process the `AssistRequest` messages."""

    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_IN_CONFIG_FIELD_NUMBER: _builtins.int
    TEXT_QUERY_FIELD_NUMBER: _builtins.int
    AUDIO_OUT_CONFIG_FIELD_NUMBER: _builtins.int
    SCREEN_OUT_CONFIG_FIELD_NUMBER: _builtins.int
    DIALOG_STATE_IN_FIELD_NUMBER: _builtins.int
    DEVICE_CONFIG_FIELD_NUMBER: _builtins.int
    DEBUG_CONFIG_FIELD_NUMBER: _builtins.int
    text_query: _builtins.str
    """The text input to be sent to the Assistant. This can be populated from a
    text interface if audio input is not available.
    """
    @_builtins.property
    def audio_in_config(self) -> Global___AudioInConfig:
        """Specifies how to process the subsequent incoming audio. Required if
        [AssistRequest.audio_in][google.assistant.embedded.v1alpha2.AssistRequest.audio_in]
        bytes will be provided in subsequent requests.
        """

    @_builtins.property
    def audio_out_config(self) -> Global___AudioOutConfig:
        """*Required* Specifies how to format the audio that will be returned."""

    @_builtins.property
    def screen_out_config(self) -> Global___ScreenOutConfig:
        """*Optional* Specifies the desired format to use when server returns a
        visual screen response.
        """

    @_builtins.property
    def dialog_state_in(self) -> Global___DialogStateIn:
        """*Required* Represents the current dialog state."""

    @_builtins.property
    def device_config(self) -> Global___DeviceConfig:
        """Device configuration that uniquely identifies a specific device."""

    @_builtins.property
    def debug_config(self) -> Global___DebugConfig:
        """*Optional* Debugging parameters for the whole `Assist` RPC."""

    def __init__(
        self,
        *,
        audio_in_config: Global___AudioInConfig | None = ...,
        text_query: _builtins.str = ...,
        audio_out_config: Global___AudioOutConfig | None = ...,
        screen_out_config: Global___ScreenOutConfig | None = ...,
        dialog_state_in: Global___DialogStateIn | None = ...,
        device_config: Global___DeviceConfig | None = ...,
        debug_config: Global___DebugConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config", "debug_config", b"debug_config", "device_config", b"device_config", "dialog_state_in", b"dialog_state_in", "screen_out_config", b"screen_out_config", "text_query", b"text_query", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config", "debug_config", b"debug_config", "device_config", b"device_config", "dialog_state_in", b"dialog_state_in", "screen_out_config", b"screen_out_config", "text_query", b"text_query", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["audio_in_config", "text_query"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___AssistConfig: _TypeAlias = AssistConfig  # noqa: Y015

@_typing.final
class AudioInConfig(_message.Message):
    """Specifies how to process the `audio_in` data that will be provided in
    subsequent requests. For recommended settings, see the Google Assistant SDK
    [best
    practices](https://developers.google.com/assistant/sdk/guides/service/python/best-practices/audio).
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Encoding:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EncodingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AudioInConfig._Encoding.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ENCODING_UNSPECIFIED: AudioInConfig._Encoding.ValueType  # 0
        """Not specified. Will return result [google.rpc.Code.INVALID_ARGUMENT][]."""
        LINEAR16: AudioInConfig._Encoding.ValueType  # 1
        """Uncompressed 16-bit signed little-endian samples (Linear PCM).
        This encoding includes no header, only the raw audio bytes.
        """
        FLAC: AudioInConfig._Encoding.ValueType  # 2
        """[`FLAC`](https://xiph.org/flac/documentation.html) (Free Lossless Audio
        Codec) is the recommended encoding because it is
        lossless--therefore recognition is not compromised--and
        requires only about half the bandwidth of `LINEAR16`. This encoding
        includes the `FLAC` stream header followed by audio data. It supports
        16-bit and 24-bit samples, however, not all fields in `STREAMINFO` are
        supported.
        """

    class Encoding(_Encoding, metaclass=_EncodingEnumTypeWrapper):
        """Audio encoding of the data sent in the audio message.
        Audio must be one-channel (mono).
        """

    ENCODING_UNSPECIFIED: AudioInConfig.Encoding.ValueType  # 0
    """Not specified. Will return result [google.rpc.Code.INVALID_ARGUMENT][]."""
    LINEAR16: AudioInConfig.Encoding.ValueType  # 1
    """Uncompressed 16-bit signed little-endian samples (Linear PCM).
    This encoding includes no header, only the raw audio bytes.
    """
    FLAC: AudioInConfig.Encoding.ValueType  # 2
    """[`FLAC`](https://xiph.org/flac/documentation.html) (Free Lossless Audio
    Codec) is the recommended encoding because it is
    lossless--therefore recognition is not compromised--and
    requires only about half the bandwidth of `LINEAR16`. This encoding
    includes the `FLAC` stream header followed by audio data. It supports
    16-bit and 24-bit samples, however, not all fields in `STREAMINFO` are
    supported.
    """

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    encoding: Global___AudioInConfig.Encoding.ValueType
    """*Required* Encoding of audio data sent in all `audio_in` messages."""
    sample_rate_hertz: _builtins.int
    """*Required* Sample rate (in Hertz) of the audio data sent in all `audio_in`
    messages. Valid values are from 16000-24000, but 16000 is optimal.
    For best results, set the sampling rate of the audio source to 16000 Hz.
    If that's not possible, use the native sample rate of the audio source
    (instead of re-sampling).
    """
    def __init__(
        self,
        *,
        encoding: Global___AudioInConfig.Encoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioInConfig: _TypeAlias = AudioInConfig  # noqa: Y015

@_typing.final
class AudioOutConfig(_message.Message):
    """Specifies the desired format for the server to use when it returns
    `audio_out` messages.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Encoding:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EncodingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AudioOutConfig._Encoding.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ENCODING_UNSPECIFIED: AudioOutConfig._Encoding.ValueType  # 0
        """Not specified. Will return result [google.rpc.Code.INVALID_ARGUMENT][]."""
        LINEAR16: AudioOutConfig._Encoding.ValueType  # 1
        """Uncompressed 16-bit signed little-endian samples (Linear PCM)."""
        MP3: AudioOutConfig._Encoding.ValueType  # 2
        """MP3 audio encoding. The sample rate is encoded in the payload."""
        OPUS_IN_OGG: AudioOutConfig._Encoding.ValueType  # 3
        """Opus-encoded audio wrapped in an ogg container. The result will be a
        file which can be played natively on Android and in some browsers (such
        as Chrome). The quality of the encoding is considerably higher than MP3
        while using the same bitrate. The sample rate is encoded in the payload.
        """

    class Encoding(_Encoding, metaclass=_EncodingEnumTypeWrapper):
        """Audio encoding of the data returned in the audio message. All encodings are
        raw audio bytes with no header, except as indicated below.
        """

    ENCODING_UNSPECIFIED: AudioOutConfig.Encoding.ValueType  # 0
    """Not specified. Will return result [google.rpc.Code.INVALID_ARGUMENT][]."""
    LINEAR16: AudioOutConfig.Encoding.ValueType  # 1
    """Uncompressed 16-bit signed little-endian samples (Linear PCM)."""
    MP3: AudioOutConfig.Encoding.ValueType  # 2
    """MP3 audio encoding. The sample rate is encoded in the payload."""
    OPUS_IN_OGG: AudioOutConfig.Encoding.ValueType  # 3
    """Opus-encoded audio wrapped in an ogg container. The result will be a
    file which can be played natively on Android and in some browsers (such
    as Chrome). The quality of the encoding is considerably higher than MP3
    while using the same bitrate. The sample rate is encoded in the payload.
    """

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    VOLUME_PERCENTAGE_FIELD_NUMBER: _builtins.int
    encoding: Global___AudioOutConfig.Encoding.ValueType
    """*Required* The encoding of audio data to be returned in all `audio_out`
    messages.
    """
    sample_rate_hertz: _builtins.int
    """*Required* The sample rate in Hertz of the audio data returned in
    `audio_out` messages. Valid values are: 16000-24000.
    """
    volume_percentage: _builtins.int
    """*Required* Current volume setting of the device's audio output.
    Valid values are 1 to 100 (corresponding to 1% to 100%).
    """
    def __init__(
        self,
        *,
        encoding: Global___AudioOutConfig.Encoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
        volume_percentage: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz", "volume_percentage", b"volume_percentage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioOutConfig: _TypeAlias = AudioOutConfig  # noqa: Y015

@_typing.final
class ScreenOutConfig(_message.Message):
    """Specifies the desired format for the server to use when it returns
    `screen_out` response.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _ScreenMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ScreenModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ScreenOutConfig._ScreenMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SCREEN_MODE_UNSPECIFIED: ScreenOutConfig._ScreenMode.ValueType  # 0
        """No video mode specified.
        The Assistant may respond as if in `OFF` mode.
        """
        OFF: ScreenOutConfig._ScreenMode.ValueType  # 1
        """Screen is off (or has brightness or other settings set so low it is
        not visible). The Assistant will typically not return a screen response
        in this mode.
        """
        PLAYING: ScreenOutConfig._ScreenMode.ValueType  # 3
        """The Assistant will typically return a partial-screen response in this
        mode.
        """

    class ScreenMode(_ScreenMode, metaclass=_ScreenModeEnumTypeWrapper):
        """Possible modes for visual screen-output on the device."""

    SCREEN_MODE_UNSPECIFIED: ScreenOutConfig.ScreenMode.ValueType  # 0
    """No video mode specified.
    The Assistant may respond as if in `OFF` mode.
    """
    OFF: ScreenOutConfig.ScreenMode.ValueType  # 1
    """Screen is off (or has brightness or other settings set so low it is
    not visible). The Assistant will typically not return a screen response
    in this mode.
    """
    PLAYING: ScreenOutConfig.ScreenMode.ValueType  # 3
    """The Assistant will typically return a partial-screen response in this
    mode.
    """

    SCREEN_MODE_FIELD_NUMBER: _builtins.int
    screen_mode: Global___ScreenOutConfig.ScreenMode.ValueType
    """Current visual screen-mode for the device while issuing the query."""
    def __init__(
        self,
        *,
        screen_mode: Global___ScreenOutConfig.ScreenMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["screen_mode", b"screen_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenOutConfig: _TypeAlias = ScreenOutConfig  # noqa: Y015

@_typing.final
class DialogStateIn(_message.Message):
    """Provides information about the current dialog state."""

    DESCRIPTOR: _descriptor.Descriptor

    CONVERSATION_STATE_FIELD_NUMBER: _builtins.int
    LANGUAGE_CODE_FIELD_NUMBER: _builtins.int
    DEVICE_LOCATION_FIELD_NUMBER: _builtins.int
    IS_NEW_CONVERSATION_FIELD_NUMBER: _builtins.int
    conversation_state: _builtins.bytes
    """*Required* This field must always be set to the
    [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state]
    value that was returned in the prior `Assist` RPC. It should only be
    omitted (field not set) if there was no prior `Assist` RPC because this is
    the first `Assist` RPC made by this device after it was first setup and/or
    a factory-default reset.
    """
    language_code: _builtins.str
    """*Required* Language of the request in
    [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47) (for example,
    "en-US"). See [Language
    Support](https://developers.google.com/assistant/sdk/reference/rpc/languages)
    for more information. If you have selected a language for this `device_id`
    using the
    [Settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings)
    menu in your phone's Google Assistant app, that selection will override
    this value.
    """
    is_new_conversation: _builtins.bool
    """*Optional* If true, the server will treat the request as a new conversation
    and not use state from the prior request. Set this field to true when the
    conversation should be restarted, such as after a device reboot, or after a
    significant lapse of time since the prior query.
    """
    @_builtins.property
    def device_location(self) -> Global___DeviceLocation:
        """*Optional* Location of the device where the query originated."""

    def __init__(
        self,
        *,
        conversation_state: _builtins.bytes = ...,
        language_code: _builtins.str = ...,
        device_location: Global___DeviceLocation | None = ...,
        is_new_conversation: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device_location", b"device_location"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conversation_state", b"conversation_state", "device_location", b"device_location", "is_new_conversation", b"is_new_conversation", "language_code", b"language_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DialogStateIn: _TypeAlias = DialogStateIn  # noqa: Y015

@_typing.final
class DeviceConfig(_message.Message):
    """*Required* Fields that identify the device to the Assistant.

    See also:

    *   [Register a Device - REST
    API](https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual)
    *   [Device Model and Instance
    Schemas](https://developers.google.com/assistant/sdk/reference/device-registration/model-and-instance-schemas)
    *   [Device
    Proto](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.devices.v1alpha2#device)
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    DEVICE_MODEL_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    """*Required* Unique identifier for the device. The id length must be 128
    characters or less. Example: DBCDW098234. This MUST match the device_id
    returned from device registration. This device_id is used to match against
    the user's registered devices to lookup the supported traits and
    capabilities of this device. This information should not change across
    device reboots. However, it should not be saved across
    factory-default resets.
    """
    device_model_id: _builtins.str
    """*Required* Unique identifier for the device model. The combination of
    device_model_id and device_id must have been previously associated through
    device registration.
    """
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        device_model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "device_model_id", b"device_model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceConfig: _TypeAlias = DeviceConfig  # noqa: Y015

@_typing.final
class AudioOut(_message.Message):
    """The audio containing the Assistant's response to the query. Sequential chunks
    of audio data are received in sequential `AssistResponse` messages.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_DATA_FIELD_NUMBER: _builtins.int
    audio_data: _builtins.bytes
    """*Output-only* The audio data containing the Assistant's response to the
    query. Sequential chunks of audio data are received in sequential
    `AssistResponse` messages.
    """
    def __init__(
        self,
        *,
        audio_data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_data", b"audio_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioOut: _TypeAlias = AudioOut  # noqa: Y015

@_typing.final
class ScreenOut(_message.Message):
    """The Assistant's visual output response to query. Enabled by
    `screen_out_config`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Format:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ScreenOut._Format.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: ScreenOut._Format.ValueType  # 0
        """No format specified."""
        HTML: ScreenOut._Format.ValueType  # 1
        """Data will contain a fully-formed HTML5 layout encoded in UTF-8, e.g.
        `<html><body><div>...</div></body></html>`. It is intended to be rendered
        along with the audio response. Note that HTML5 doctype should be included
        in the actual HTML data.
        """

    class Format(_Format, metaclass=_FormatEnumTypeWrapper):
        """Possible formats of the screen data."""

    FORMAT_UNSPECIFIED: ScreenOut.Format.ValueType  # 0
    """No format specified."""
    HTML: ScreenOut.Format.ValueType  # 1
    """Data will contain a fully-formed HTML5 layout encoded in UTF-8, e.g.
    `<html><body><div>...</div></body></html>`. It is intended to be rendered
    along with the audio response. Note that HTML5 doctype should be included
    in the actual HTML data.
    """

    FORMAT_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    format: Global___ScreenOut.Format.ValueType
    """*Output-only* The format of the provided screen data."""
    data: _builtins.bytes
    """*Output-only* The raw screen data to be displayed as the result of the
    Assistant query.
    """
    def __init__(
        self,
        *,
        format: Global___ScreenOut.Format.ValueType = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "format", b"format"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenOut: _TypeAlias = ScreenOut  # noqa: Y015

@_typing.final
class DeviceAction(_message.Message):
    """The response returned to the device if the user has triggered a Device
    Action. For example, a device which supports the query *Turn on the light*
    would receive a `DeviceAction` with a JSON payload containing the semantics
    of the request.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_REQUEST_JSON_FIELD_NUMBER: _builtins.int
    device_request_json: _builtins.str
    """JSON containing the device command response generated from the triggered
    Device Action grammar. The format is given by the
    `action.devices.EXECUTE` intent for a given
    [trait](https://developers.google.com/assistant/sdk/reference/traits/).
    """
    def __init__(
        self,
        *,
        device_request_json: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_request_json", b"device_request_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceAction: _TypeAlias = DeviceAction  # noqa: Y015

@_typing.final
class SpeechRecognitionResult(_message.Message):
    """The estimated transcription of a phrase the user has spoken. This could be
    a single segment or the full guess of the user's spoken query.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    STABILITY_FIELD_NUMBER: _builtins.int
    transcript: _builtins.str
    """*Output-only* Transcript text representing the words that the user spoke."""
    stability: _builtins.float
    """*Output-only* An estimate of the likelihood that the Assistant will not
    change its guess about this result. Values range from 0.0 (completely
    unstable) to 1.0 (completely stable and final). The default of 0.0 is a
    sentinel value indicating `stability` was not set.
    """
    def __init__(
        self,
        *,
        transcript: _builtins.str = ...,
        stability: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stability", b"stability", "transcript", b"transcript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpeechRecognitionResult: _TypeAlias = SpeechRecognitionResult  # noqa: Y015

@_typing.final
class DialogStateOut(_message.Message):
    """The dialog state resulting from the user's query. Multiple of these messages
    may be received.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _MicrophoneMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MicrophoneModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DialogStateOut._MicrophoneMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MICROPHONE_MODE_UNSPECIFIED: DialogStateOut._MicrophoneMode.ValueType  # 0
        """No mode specified."""
        CLOSE_MICROPHONE: DialogStateOut._MicrophoneMode.ValueType  # 1
        """The service is not expecting a follow-on question from the user.
        The microphone should remain off until the user re-activates it.
        """
        DIALOG_FOLLOW_ON: DialogStateOut._MicrophoneMode.ValueType  # 2
        """The service is expecting a follow-on question from the user. The
        microphone should be re-opened when the `AudioOut` playback completes
        (by starting a new `Assist` RPC call to send the new audio).
        """

    class MicrophoneMode(_MicrophoneMode, metaclass=_MicrophoneModeEnumTypeWrapper):
        """Possible states of the microphone after a `Assist` RPC completes."""

    MICROPHONE_MODE_UNSPECIFIED: DialogStateOut.MicrophoneMode.ValueType  # 0
    """No mode specified."""
    CLOSE_MICROPHONE: DialogStateOut.MicrophoneMode.ValueType  # 1
    """The service is not expecting a follow-on question from the user.
    The microphone should remain off until the user re-activates it.
    """
    DIALOG_FOLLOW_ON: DialogStateOut.MicrophoneMode.ValueType  # 2
    """The service is expecting a follow-on question from the user. The
    microphone should be re-opened when the `AudioOut` playback completes
    (by starting a new `Assist` RPC call to send the new audio).
    """

    SUPPLEMENTAL_DISPLAY_TEXT_FIELD_NUMBER: _builtins.int
    CONVERSATION_STATE_FIELD_NUMBER: _builtins.int
    MICROPHONE_MODE_FIELD_NUMBER: _builtins.int
    VOLUME_PERCENTAGE_FIELD_NUMBER: _builtins.int
    supplemental_display_text: _builtins.str
    """*Output-only* Supplemental display text from the Assistant. This could be
    the same as the speech spoken in `AssistResponse.audio_out` or it could
    be some additional information which aids the user's understanding.
    """
    conversation_state: _builtins.bytes
    """*Output-only* State information for the subsequent `Assist` RPC. This
    value should be saved in the client and returned in the
    [`DialogStateIn.conversation_state`](#dialogstatein) field with the next
    `Assist` RPC. (The client does not need to interpret or otherwise use this
    value.) This information should be saved across device reboots. However,
    this value should be cleared (not saved in the client) during a
    factory-default reset.
    """
    microphone_mode: Global___DialogStateOut.MicrophoneMode.ValueType
    """*Output-only* Specifies the mode of the microphone after this `Assist`
    RPC is processed.
    """
    volume_percentage: _builtins.int
    """*Output-only* Updated volume level. The value will be 0 or omitted
    (indicating no change) unless a voice command such as *Increase the volume*
    or *Set volume level 4* was recognized, in which case the value will be
    between 1 and 100 (corresponding to the new volume level of 1% to 100%).
    Typically, a client should use this volume level when playing the
    `audio_out` data, and retain this value as the current volume level and
    supply it in the `AudioOutConfig` of the next `AssistRequest`. (Some
    clients may also implement other ways to allow the current volume level to
    be changed, for example, by providing a knob that the user can turn.)
    """
    def __init__(
        self,
        *,
        supplemental_display_text: _builtins.str = ...,
        conversation_state: _builtins.bytes = ...,
        microphone_mode: Global___DialogStateOut.MicrophoneMode.ValueType = ...,
        volume_percentage: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conversation_state", b"conversation_state", "microphone_mode", b"microphone_mode", "supplemental_display_text", b"supplemental_display_text", "volume_percentage", b"volume_percentage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DialogStateOut: _TypeAlias = DialogStateOut  # noqa: Y015

@_typing.final
class DebugConfig(_message.Message):
    """Debugging parameters for the current request."""

    DESCRIPTOR: _descriptor.Descriptor

    RETURN_DEBUG_INFO_FIELD_NUMBER: _builtins.int
    return_debug_info: _builtins.bool
    """When this field is set to true, the `debug_info` field in `AssistResponse`
    may be populated. However it will significantly increase latency of
    responses. Do not set this field true in production code.
    """
    def __init__(
        self,
        *,
        return_debug_info: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_debug_info", b"return_debug_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DebugConfig: _TypeAlias = DebugConfig  # noqa: Y015

@_typing.final
class DeviceLocation(_message.Message):
    """There are three sources of locations. They are used with this precedence:

    1. This `DeviceLocation`, which is primarily used for mobile devices with
       GPS .
    2. Location specified by the user during device setup; this is per-user, per
       device. This location is used if `DeviceLocation` is not specified.
    3. Inferred location based on IP address. This is used only if neither of the
       above are specified.
    oneof type {
      // Latitude and longitude of device.
      google.type.LatLng coordinates = 1;
    }
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceLocation: _TypeAlias = DeviceLocation  # noqa: Y015
